service: serverless-crud-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}-items
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions: ${file(./serverless/functions.yml)}
resources: ${file(./serverless/resources.yml)}

plugins:
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - tests/**
    - README.md
    - .gitignore
    - public/**
    - docs/**
